[colors.primary]
background = "#24292F"
foreground = "#C0C8D8"

[colors.cursor]
text = "#24292F"
cursor = "#C0C8D8"

[colors.selection]
text = "#C0C8D8"
background = "#3B424E"

[colors.normal]
black   = "#191D24"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#5E81AC"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#C0C8D8"

[colors.bright]
black   = "#3B424E"
red     = "#C1626B"
green   = "#B1D196"
yellow  = "#EFDB9F"
blue    = "#5E81AC"
magenta = "#BE9FBC"
cyan    = "#9FC6C6"
white   = "#D8DEEB"

[colors.dim]
black   = "#191D24"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#5E81AC"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#C0C8D8"

# Indexed colors (shell / truecolor fallback)
[[colors.indexed_colors]]
index = 16
color = '#D08770' # orange

[[colors.indexed_colors]]
index = 17
color = '#BF616A' # deep red

[[colors.indexed_colors]]
index = 18
color = '#191D24' # dark background

[[colors.indexed_colors]]
index = 19
color = '#24292F'

[[colors.indexed_colors]]
index = 20
color = '#3B424E'

[[colors.indexed_colors]]
index = 21
color = '#5E81AC'

[[colors.indexed_colors]]
index = 22
color = '#A3BE8C'

[[colors.indexed_colors]]
index = 23
color = '#8FBCBB'

